<?php

/**
 * @file
 * Contains page_menu_reorder.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function page_menu_reorder_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the test_module module.
    case 'help.page.page_menu_reorder':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Page Menu Reorder module helps to rearrange menu links of a page. A new reorder tab is
      added onto a page if the page has menu links.') . '</p>';
      $output .= '<p>' . t('Normally we reorder the menu links on the menu administration page admin/structure/menu/manage/main. 
      But it’s not so easier for a large site with hundreds of menu links. Also we need to restrict access to the 
      global menu admin page. This module helps to overcome the issues.') . '</p>';
      $output .= '<p>' . t('This module works with the menu `Main navigation` for now. This could be easily extended to work with other menus.') . '</p>';
      return $output;

    default:
  }
}
