<?php
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
/**
 * Add Site name admin field in social login tab.
 * @param $form
 * @param $form_state
 * @param $form_id
 * @return mixed
 */
function sso_form_sociallogin_settings_alter(&$form, FormStateInterface $form_state) {
  $config = \Drupal::config('sociallogin.settings');
  $form['lr_settings']['sso_site_name'] = array(
    '#type' => 'textfield',
    '#title' => t('LoginRadius Site Name'),
    '#default_value' => $config->get('sso_site_name'),
    '#weight' => -10,
    '#required' => TRUE,
    '#description' => t('You can find the Site Name into your LoginRadius user account'),
  );
  //return $form;
}

/**
 * Add required sso js files to page.
 *
 * @param $vars
 * @param $hook
 */
function sso_page_attachments(&$page) {
  global $user;
  $config = \Drupal::config('sso.settings');
  $sl_config = \Drupal::config('sociallogin.settings');

  $site_name = $sl_config->get('sso_site_name');
  $sso_secure_cookie = $config->get('sso_enable_secure_cookie');

  if ($config->get('sso_enable') == 1 && !empty($site_name)) {
   /* if (drupal_is_front_page()) {
      $GLOBALS['conf']['cache'] = FALSE;
    }*/
    $user = \Drupal::currentUser()->getRoles();

    $path = parse_url(Url::fromRoute('<front>')->toString());
    $sso_path = $path['path'];
    $my_settings['sso_path'] = $sso_path;
    $my_settings['site_name'] = $site_name;
    $my_settings['secure_cookie'] = (($sso_secure_cookie == 1) ? 'https:' : '');
    
   
 $my_settings['logout'] = Url::fromRoute('<front>')->setAbsolute()->toString();
      if ( \Drupal::currentUser()
      ->isAnonymous()) {
        $my_settings['redirect'] = true;
        $my_settings['login_url'] = Url::fromRoute('user.login')->setAbsolute()->toString();
        $my_settings['callback']= urldecode(userregistration_get_callback_url());
      }
      if (  !\Drupal::currentUser()->isAnonymous() && !in_array("administrator", $user)) {
    
        $logout = Url::fromRoute('user.logout')->setAbsolute()->toString();
        $logout = (strpos($logout, '?') == TRUE ? ($logout . '&notlogged=1') : ($logout . '?notlogged=1'));
       
        $my_settings['isNotLoginThenLogout'] = true;
        $my_settings['logout_url'] = $logout;
        
      }    

     $page['#attached']['drupalSettings']['sso']  = $my_settings;
    $page['#attached']['library'][] = 'sso/drupal.coresso';
  }
}
function sso_add_extra_sociallogin_config_settings(){
  return array('sso_site_name');
}
