<?php
/**
 * Implements hook_schema().
 */
function userregistration_schema() {
 if (!\Drupal\Core\Database\Database::getConnection()->schema()->fieldExists('users', 'lr_raas_uid')) {
    \Drupal\Core\Database\Database::getConnection()->schema()->addField('users', 'lr_raas_uid', array(
      'type' => 'varchar',
      'length' => 255,
      'not null' => FALSE,
      'default' => '',
    ));
  } 
}
function userregistration_install(){
	 module_set_weight('userregistration', 4);
}

