better_login_form.admin:
  title: 'Better login form Configuration '
  description: ' you can configure the label, description and login button of the default user login form. '
  parent: system.admin_config_ui
  url: internal:/admin/config/user-interface/better-login-form