name: Better login Form Config
description: 'you can configure the label, description and login button of the default user login form '
# core: 8.x
type: module
configure: fancy_login.settings
package: User Login Better
dependencies:
- user
type: module

# Information added by Drupal.org packaging script on 2018-07-13
# version: '8.x-1.0'
# core: '8.x'
# project: 'better_login_form_config'
# datestamp: 1531446526

# Information added by Drupal.org packaging script on 2018-07-14
version: '8.x-1.1'
core: '8.x'
project: 'better_login_form_config'
datestamp: 1531556025
