<?php

use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Form\FormStateInterface;

 
/**
 * Add required hostedpage js files to page.
 *
 * @param $vars
 * @param $hook
 */
function hostedpage_page_attachments(&$page) { 
  $user = \Drupal::currentUser(); 
  $config = \Drupal::config('hostedpage.settings');
  $sl_config = \Drupal::config('sociallogin.settings');
   
  $destination = array('destination' => "destination"); 
  $current_alias = \Drupal::service('path.current')->getPath();
  $enablehosted = $config->get('lr_hosted_page_enable');
  $site_name = $sl_config->get('sso_site_name');

  if((isset($enablehosted) && $enablehosted == '1') && (isset($site_name) && $site_name != '')){  
  if (\Drupal::currentUser()->isAnonymous()) {    
  $baseurl = Url::fromRoute('<front>')->setAbsolute()->toString();
      if(($current_alias == '/user/login') && (isset($_GET['destination']) && $_GET['destination'] == $destination['destination']) || ($current_alias == '/user/login')){
        $url = 'https://'.$site_name.'.hub.loginradius.com/auth.aspx?action=login&return_url='.urldecode(userregistration_get_callback_url());
        $response = new RedirectResponse($url);
        return $response->send();  
            
      } else if(($current_alias == '/user/register') && (isset($_GET['destination']) && $_GET['destination'] == $destination['destination']) || ($current_alias == '/user/register')){
          $url = 'https://'.$site_name.'.hub.loginradius.com/auth.aspx?action=register&return_url='.urldecode(userregistration_get_callback_url());
          $response = new RedirectResponse($url);
          return $response->send();                  
      } else if($current_alias == '/user/password'){
            $response = new RedirectResponse('https://'.$site_name.'.hub.loginradius.com/auth.aspx?action=forgotpassword&return_url='.urldecode(userregistration_get_callback_url()));
            return $response->send();              
      } 
    } else {     
      if($current_alias == '/user/'.$user->id().'/edit'){       
        $response = new RedirectResponse('https://'.$site_name.'.hub.loginradius.com/auth.aspx?action=profile');
         return $response->send();
   
      } else if($current_alias == '/user/'.$user->id().'/changepassword'){
          $response = new RedirectResponse('https://'.$site_name.'.hub.loginradius.com/auth.aspx?action=profile');
          return $response->send();
      } 
    }    
  } 
}
 
function hostedpage_user_logout($account) {  
    $config = \Drupal::config('sso.settings');    
    if ($config->get('sso_enable') != 1) { 
    $sl_config = \Drupal::config('sociallogin.settings');
    $site_name = $sl_config->get('sso_site_name');
    $baseurl = Url::fromRoute('<front>')->setAbsolute()->toString();
    $response = new RedirectResponse('https://'.$site_name.'.hub.loginradius.com/auth.aspx?action=logout&return_url='.$baseurl);
    return $response->send(); 
    }
}

