fancy_login.settings:
  type: config_object
  mapping:
    screen_fade_color:
      type: string
      label: 'Screen Fade Color'
    screen_fade_z_index:
      type: integer
      label: 'Z-Index'
    login_box_background_color:
      type: string
      label: 'Login Box Background Color'
    login_box_text_color:
      type: string
      label: 'Login Box Text Color'
    login_box_border_color:
      type: string
      label: 'Login Box Border Color'
    login_box_border_width:
      type: string
      label: 'Login Box Border Width'
    login_box_border_style:
      type: string
      label: 'Login Box Border Style'
    hide_objects:
      type: boolean
      label: 'Hide Objects'
    dim_fade_time:
      type: integer
      label: 'Dimmer Fade Time'
    login_box_fade_time:
      type: integer
      label: 'Login Box Fade Time'
    no_redirect:
      type: boolean
      label: 'No Redirect'
    https:
      type: boolean
      label: 'HTTPS'
    icon_position:
      type: integer
      label: 'Icon Position'
